language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

services:
  - memcached
  - redis-server

global:
  - REPORT_EXIT_STATUS=1

before_install:
  - composer self-update
  - composer install --dev

before_script:
  - if [[ "$(php -v | grep 'PHP 5')" ]]; then echo yes | pecl install apcu-4.0.8; fi
  - if [[ "$(php -v | grep 'PHP 7')" ]]; then echo yes | pecl install apcu; fi
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - vendor/bin/phpunit

matrix:
  fast_finish: true