language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

services:
  - memcached
  - redis-server

before_install:
  - if [[ $TRAVIS_PHP_VERSION = "5.6" ]]; then echo yes | pecl install apcu-4.0.11; fi
  - if [[ $TRAVIS_PHP_VERSION = "7.0" ]]; then echo yes | pecl install apcu-5.1.5; fi

before_script:
  - composer self-update
  - composer install --dev

script:
  - vendor/bin/phpunit

matrix:
  fast_finish: true