language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

services:
  - memcached
  - redis-server

global:
  - REPORT_EXIT_STATUS=1

before_install:
  - if [[ $TRAVIS_PHP_VERSION = "5.6" ]]; then echo yes | pecl install apcu-4.0.11; fi
  - if [[ $TRAVIS_PHP_VERSION = "7.0" ]]; then echo yes | pecl install apcu-5.1.7; fi
  - if [[ $TRAVIS_PHP_VERSION = "7.1" ]]; then echo yes | pecl install apcu-5.1.7; fi
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then phpenv config-add install/travis-$TRAVIS_PHP_VERSION.ini; fi
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer self-update
  - composer install --dev

script:
  - vendor/bin/phpunit

matrix:
  fast_finish: true