language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

services:
  - memcached
  - redis-server

before_install:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]] ; then echo yes | pecl install apcu-4.0.10; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then pecl config-set preferred_state beta; echo yes | pecl install apcu; fi;
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then PHPUNIT_FLAGS="--coverage-clover clover.xml"; fi
  - composer self-update
  - composer install --dev

script:
  - vendor/bin/phpunit

matrix:
  fast_finish: true